# Generated by Django 4.0.7 on 2022-09-22 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('placed_on', models.DateField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ORDER_PLACED', 'Placed'), ('ORDER_IN_PROGRESS', 'Progress'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('TRANSFER', 'Transfer'), ('CASH', 'Cash')], max_length=10)),
                ('delivery_option', models.CharField(choices=[('PICKUP', 'Pickup'), ('HOUSE_DELIVERY', 'House')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.product')),
            ],
        ),
    ]
